topcore:

  database:

    enabled: true

    driver: H2

    mode: FILE

    r2dbc:

      url: r2dbc:h2:file:///./data/topcoredb?options=AUTO_SERVER=TRUE

      username: sa

      password:

    pool:

      enabled: true

      initialSize: 5

      maxSize: 20

      maxIdleTimeSeconds: 300

    persistence:

      transaction:

        enabled: true

      message:

        enabled: true