package com.rkp.topcore.core.database.schema;

public final class DatabaseSchema {

    private DatabaseSchema() {
    }


    public static final String CREATE_TRANSACTION_TABLE =

            """
            CREATE TABLE IF NOT EXISTS topcore_transaction (

                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                correlation_id VARCHAR(100) NOT NULL,

                message_id VARCHAR(200),

                session_id VARCHAR(100),

                terminal_id VARCHAR(100),

                source_system VARCHAR(100),

                status VARCHAR(50),

                started_at TIMESTAMP,

                completed_at TIMESTAMP,

                latency_ms BIGINT,

                created_at TIMESTAMP

            )
            """;


    public static final String CREATE_MESSAGE_TABLE =

            """
            CREATE TABLE IF NOT EXISTS topcore_message (

                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                transaction_id BIGINT NOT NULL,

                system_name VARCHAR(100) NOT NULL,

                direction VARCHAR(20) NOT NULL,

                message_type VARCHAR(50),

                payload CLOB,

                masked_payload CLOB,

                status VARCHAR(50),

                latency_ms BIGINT,

                created_at TIMESTAMP,

                CONSTRAINT fk_topcore_message_transaction
                    FOREIGN KEY (transaction_id)
                    REFERENCES topcore_transaction(id)

            )
            """;


    public static final String CREATE_TRANSACTION_CORRELATION_INDEX =

            """
            CREATE INDEX IF NOT EXISTS
            idx_topcore_transaction_correlation

            ON topcore_transaction(correlation_id)
            """;


    public static final String CREATE_TRANSACTION_MESSAGE_INDEX =

            """
            CREATE INDEX IF NOT EXISTS
            idx_topcore_transaction_message

            ON topcore_transaction(message_id)
            """;


    public static final String CREATE_MESSAGE_TRANSACTION_INDEX =

            """
            CREATE INDEX IF NOT EXISTS
            idx_topcore_message_transaction

            ON topcore_message(transaction_id)
            """;


    public static final String CREATE_MESSAGE_SYSTEM_INDEX =

            """
            CREATE INDEX IF NOT EXISTS
            idx_topcore_message_system

            ON topcore_message(system_name)
            """;

}